app:
  name: "im"
  mode: "dev"
  port: 8081
  start_time: "2026-03-10"
  machine_id: 1
mysql:
  host: "192.168.78.200"
  port: 3307
  user: "root"
  password: "sta_go"
  dbname: "im"
log:
  level: "debug"
  filename: "bug.log"
  max_size: 300
  max_age: 30
  max_backups: 7
redis:
  host: "192.168.78.200"
  port: 6379
  db: 0
  pool_size: 1000
  password: "sta_go"

email:
  from: "2530225403@qq.com"
  smtp_host: "smtp.qq.com"
  smtp_port: 587
  secret_key: "xqlcaiflfygqdjae"

auth:
  jwt_expire: 24